name: client-stack

services:

  redis:
    image: docker.io/redis:7-alpine
    container_name: immich_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ./immich/postgres:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
      
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      REDIS_HOSTNAME: redis
      TZ: ${TZ}
      IMMICH_TELEMETRY_INCLUDE: all
      IMMICH_EXTERNAL_URL: https://photos-${DEVICE_ID}.${BASE_DOMAIN}
    volumes:
      - ./immich/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2283:2283"
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    healthcheck:
      disable: false

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - immich-server
    # ports:
    #   - "8080:80" # testing only

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yaml run
    env_file:
      - .env
    volumes:
      - ./cloudflared:/etc/cloudflared:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - caddy

  immichframe:
    image: ghcr.io/immichframe/immichframe:latest
    container_name: immichframe
    restart: unless-stopped
    env_file:
      - .env
    # environment:
      # IMMICHFRAME_CONFIG_PATH: /app/Config
    volumes:
      - ./immichframe/Config:/app/Config:ro
    ports:
      - "8080:8080"
    depends_on:
      - immich-server

  # immich-kiosk:
  #   image: ghcr.io/damongolding/immich-kiosk:latest
  #   container_name: immich-kiosk
  #   restart: unless-stopped
  #   tty: true
  #   env_file:
  #     - .env
  #   environment:
  #     KIOSK_IMMICH_API_KEY: ${KIOSK_IMMICH_API_KEY}
  #     KIOSK_IMMICH_URL: ${KIOSK_IMMICH_URL}
  #   volumes:
  #     - ./immich-kiosk/config:/config
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #     database:
  #       condition: service_healthy
  #     immich-server:
  #       condition: service_started
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 10s

#################################
  # immich-machine-learning:
  #   image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
  #   container_name: immich_machine_learning
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./immich/model-cache:/cache
  #   healthcheck:
  #     disable: false

